[package]
name = "cincinnati"
version = "0.1.0"
authors = ["Alex Crawford <crawford@redhat.com>"]
edition = "2018"

[dependencies]
actix-web = "^1.0.2"
commons = { path = "../commons" }
custom_debug_derive = "^0.1.7"
daggy = { version = "^0.6.0", features = [ "serde-1" ] }
env_logger = "^0.6.0"
failure = "^0.1.1"
futures = "0.1"
futures-locks = "0.3.3"
lazy_static = "^1.2.0"
log = "^0.4.3"
prometheus = { git = "https://github.com/pingcap/rust-prometheus.git", rev = "6a02b0d2943f8fffce672e236e22c6f925184d93"}
protobuf = "2.0"
quay = { path = "../quay" }
regex = "^1.1.0"
reqwest = "^0.9.19"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "^1.0.22"
smart-default = "^0.5.2"
tokio = "0.1"
toml = "^0.4.10"
url = "^1.7.2"
semver = "^0.9.0"

[dev-dependencies]
maplit = "^1.0.2"
mockito = "^0.20.0"
serde_json = "1.0.22"
twoway = "^0.2"

[build-dependencies]
protoc-rust = "2.8"

[features]
codegen-protoc = []
test-net = []
test-net-private = []
