[package]
name = "policy-engine"
version = "0.1.0"
authors = ["Alex Crawford <crawford@redhat.com>"]

[dependencies]
actix = "^0.7.6"
actix-web = "^0.7.8"
cincinnati = { path = "../cincinnati" }
commons = { path = "../commons" }
env_logger = "^0.6.0"
failure = "^0.1.1"
futures = "^0.1.23"
hyper = "^0.12.6"
lazy_static = "^1.2.0"
log = "^0.4.3"
prometheus = "^0.4.2"
semver = "^0.9.0"
serde_json = "^1.0.22"
structopt = "^0.2.10"
openapiv3 = "0.1"

[dev-dependencies]
tokio = "^0.1"