[package]
name = "policy-engine"
version = "0.1.0"
authors = ["Alex Crawford <crawford@redhat.com>"]

[dependencies]
actix-web = "^0.7.8"
cincinnati = { path = "../cincinnati" }
env_logger = "^0.5.10"
failure = "^0.1.1"
futures = "^0.1.23"
hyper = "^0.12.6"
log = "^0.4.3"
semver = "^0.9.0"
serde_json = "^1.0.22"
structopt = "^0.2.10"
