[package]
name = "commons"
version = "0.1.0"
authors = ["Stefan Junker <mail@stefanjunker.de>"]
edition = "2018"

[dependencies]
actix-web = "^1.0.2"
env_logger = "^0.6.0"
failure = "^0.1.5"
lazy_static = "^1.2.0"
log = "^0.4.6"
prometheus = "^0.7.0"
serde = "^1.0.70"
serde_json = "^1.0.34"
tokio = "^0.1"
url = "^1.7.2"
futures = "^0.1"

[dev-dependencies]
tokio = "^0.1"
twoway = "^0.2"
mockito = "^0.17.1"