[package]
name = "commons"
version = "0.1.0"
authors = ["Stefan Junker <mail@stefanjunker.de>"]

[dependencies]
actix-web = "^0.7.8"
failure = "^0.1.5"
log = "^0.4.6"
serde = "^1.0.70"
serde_json = "^1.0.34"
url = "^1.7.2"
