[package]
name = "graph-builder"
version = "0.1.0"
authors = ["Alex Crawford <crawford@redhat.com>"]

[dependencies]
actix-web = "^0.7.8"
cincinnati = { path = "../cincinnati" }
commons = { path = "../commons" }
env_logger = "^0.6.0"
itertools = "^0.7.8"
failure = "^0.1.1"
flate2 = "^1.0.1"
log = "^0.4.3"
reqwest = "^0.9.0"
semver = { version = "^0.9.0", features = [ "serde" ] }
serde = "^1.0.70"
serde_derive = "^1.0.70"
serde_json = "^1.0.22"
structopt = "^0.2.10"
tar = "^0.4.16"
tokio = "0.1"
dkregistry = { git = "https://github.com/camallo/dkregistry-rs.git", rev = "a10c1aba444ce5c07e113c81160eb67c9711e327" }
futures = "0.1"
quay = { path = "../quay" }
url = "^1.7.2"
regex = "^1.1.0"


[features]
test-net = []
test-net-private = []
